server:
  port: 8002

logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: train-business
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: train
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-ot93ohbfy0002nbo.rwlb.rds.aliyuncs.com:3306/train_business?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: train_business
    password: Lyy13420357196
  data:
    redis:
      host: r-uf6ljbcdaxobsifyctpd.redis.rds.aliyuncs.com
      password: Redis000
      port: 6379
  cache:
    type: redis
    redis:
      cache-null-values: false
      key-prefix: train_cache_
      time-to-live: 60s
      use-key-prefix: true


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: statement

seata:
#  config:
#    nacos:
#      dataId: seataServer.properties
#      group: SEATA_GROUP
#      namespace: train
#      password: nacos
#      server-addr: 127.0.0.1:8848
#      username: nacos
#    type: nacos
#  registry:
#    nacos:
#      application: seata-server
#      group: SEATA_GROUP
#      namespace: train
#      password: nacos
#      server-addr: 127.0.0.1:8848
#      username: nacos
#    type: nacos
  tx-service-group: train-group
  service:
    vgroup-mapping:
      train-group: default
    grouplist:
      default: 127.0.0.1:8091