server:
  port: 8002

logging:
  config: classpath:logback-spring.xml

# sentinel默认不监控feign，需改成true，在簇点链路界面会显示资源：GET:http://business/business/hello
feign:
  sentinel:
    enabled: true

spring:
  application:
    name: train-business
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: train

#    openfeign:
#      lazy-attributes-resolution: true #开启懒加载，如果用了feign.sentinel.enabled=true一定要开启懒加载，要不会报错注入失败
#
#    sentinel:
#      web-context-unify: false #流控模式是链路时，必须关闭这个配置，默认是true，为true时可以在控台-簇点链路界面看到所有请求都在一个链路下面
#      datasource:
#        flow:
#          nacos:
#            dataId: sentinel-business-flow
#            groupId: DEFAULT_GROUP
#            namespace: train
#            ruleType: flow
#            serverAddr: localhost:8848
#        degrade:
#          nacos:
#            dataId: sentinel-business-degrade.json
#            groupId: DEFAULT_GROUP
#            namespace: train
#            ruleType: degrade
#            serverAddr: localhost:8848
#
#      transport:
#        dashboard: localhost:8080
#        port: 8719

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-ot93ohbfy0002nbo.rwlb.rds.aliyuncs.com:3306/train_business?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: train_business
    password: Lyy13420357196
  data:
    redis:
      host: r-uf6ljbcdaxobsifyctpd.redis.rds.aliyuncs.com
      password: Redis000
      port: 6379
  cache:
    type: redis
    redis:
      cache-null-values: false
      key-prefix: train_cache_
      time-to-live: 60s
      use-key-prefix: true
  profiles:
    active: dev


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: statement

#seata:
#  config:
#    nacos:
#      dataId: seataServer.properties
#      group: SEATA_GROUP
#      namespace: train
#      password: nacos
#      server-addr: 127.0.0.1:8848
#      username: nacos
#    type: nacos
#  registry:
#    nacos:
#      application: seata-server
#      group: SEATA_GROUP
#      namespace: train
#      password: nacos
#      server-addr: 127.0.0.1:8848
#      username: nacos
#    type: nacos

#  tx-service-group: train-group
#  service:
#    vgroup-mapping:
#      train-group: default
#    grouplist:
#      default: 127.0.0.1:8091

# rocketmq
#rocketmq:
#  name-server: http://localhost:9876
#  producer:
#    group: default



