server:
  port: 8001

logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: train-member

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: train


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-ot93ohbfy0002nbo.rwlb.rds.aliyuncs.com:3306/train_member?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: train_member
    password: Lyy13420357196

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


seata:
  tx-service-group: train-group
  service:
      vgroup-mapping:
        train-group: default
      grouplist:
        default: 127.0.0.1:8091
#  config:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      namespace: train
#      username: nacos
#      password: nacos
#      data-id: seataServer.properties
#      group: SEATA_GROUP
#
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: 127.0.0.1:8848
#      group: SEATA_GROUP
#      namespace: train
#      username: nacos
#      password: nacos
#      context-path: ""



