server:
  port: 8000
logging:
  config: classpath:logback-spring.xml
spring:
  cloud:
    gateway:
      routes:
        - id: member_route
          uri: lb://train-member
          predicates:
            - Path=/member/**
        - id: passenger_route
          uri: lb://train-member
          predicates:
            - Path=/passenger/**




      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600





