server:
  port: 8000
logging:
  config: classpath:logback-spring.xml
spring:
  cloud:
    gateway:
      routes:
        - id: member_route
          uri: http://localhost:8001
          predicates:
            - Path=/member/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600





